### ISSUE TITLE
Manhattan Plot function -- X-axis fit and Y-axis fit

### ISSUE THREAD

**Issue by tushardave26** [stephenturner/qqman#16]
I am currently using manhattan () function for my GWAS data and found two isuues with it.

(1) All chromosome number (i.e. 1.. 22) does not appear on x-axis though you make the font-size small with cex.axis

(2) the data points are not being fitted on Y-axis and are projected beyond the y-axis length. By reading your function, I believe, the function is calculating Y-axis limit based on max p-value. Still my data points are not well fitted.

Any quick solution to resolve this issue forever.

Thanks.

**Comment by sofiyababok** [comment]
If you'd like to connect the x and y axis, you can add a line at y = 0 using abline. The distance will remain the same, but the space won't be empty. 

tiff(filename = "file.tiff", width = 10, height = 7, units = "in", res = 200, bg = "white")
manhattan(...)
abline(h = 0,, col = "black")
dev.off()
