### ISSUE TITLE
chrlabs for non-human data and logp not working

### ISSUE THREAD

**Issue by renaschweizer** [stephenturner/qqman#22]
The chrlabs option for more chromosomes than 23 does not seem to be supported, e.g. chrlabs=c(1:38) still plots only 1:23. 

Also, logp=FALSE or logp=TRUE both still produce plots of log10P value, rather than likelihood.

**Comment by stephenturner** [comment]
Please upload some example data on https://gist.github.com/. Thanks.

**Comment by renaschweizer** [comment]
Here you go: https://gist.github.com/renaschweizer/25c23efa7d1e438b9d62

My command was manhattan(tryThis,col=c("pink","purple"),chrlabs=c(1:38),suggestiveline=neutral99,genomewideline=neutral95,logp=FALSE)

**Comment by stephenturner** [comment]
1: You've got problems with your P-values. Some are zero, others greater than 1. I was able to make a manhattan plot just fine. If you save the plot in a wider aspect ratio than I did you should be able to see all the labels.

![rplot](https://cloud.githubusercontent.com/assets/460076/5837372/b2b03db8-a14c-11e4-8d59-9db8e621158b.png)

2: `logp=FALSE` works just fine. Make sure you're using the dev version. 

![rplot01](https://cloud.githubusercontent.com/assets/460076/5837374/b7032182-a14c-11e4-862b-07d096a3a631.png)

3: `chrlabs` must be a character vector and equal in length to the number of chromosomes. You get a convenient warning message when this isn't the case. Your terminal should have told you: `You're trying to specify chromosome labels but the number of labels != number of chromosomes.` Looks to me like you have no data for chromosome 29. 

Here's the code I used:

```coffee
library(qqman)
d <- read.table("~/Desktop/plink.txt", T)

# fix your data
d <- subset(d, P>0 & P<=1)

# regular plot
manhattan(d)

# logp=FALSE works fine
manhattan(d, logp=FALSE)

# chrlabs must be character vector
manhattan(d, chrlabs=as.character(c(1:38)))

# Warning produced:
# You're trying to specify chromosome labels but the number of labels != number of chromosomes.

#whoops, you've got a problem. Look, no chromosome 29 data.
unique(d$CHR)
```

**Comment by renaschweizer** [comment]
Thank you for taking the time to work through my problem. I may have only mentioned this on your website, but the data I'm trying to plot consists of likelihood values that can be larger than 1. My understanding with the logp=FALSE options was that one could override the requirements of p being between 0 and 1. Is that not the case?

**Comment by stephenturner** [comment]
Oh, right, yes, that should work. But I did remove p-values of exactly zero.

```coffee
library(qqman) 

d <- read.table("untitled.txt", T)
d <- subset(d, P>0)
manhattan(d, logp=FALSE)
```

![rplot](https://cloud.githubusercontent.com/assets/460076/5918911/0b0f7286-a5fc-11e4-9e57-5c0872c683ac.png)
