### ISSUE TITLE
qq function: probability plot not quantile-quantile plot

### ISSUE THREAD

**Issue by sathishksrinivasan** [stephenturner/qqman#24]
The qq function in qqman package use ppoints function to get the fractions (probability points) of a set of data (expected pvalues). 

For example

ppoints(15) will give us the following fractions: Here the number 15 denotes the length of the data.

    ppoints(15)
    [1] 0.03333333 0.10000000 0.16666667 0.23333333 0.30000000 0.36666667 0.43333333   0.50000000
    [9] 0.56666667 0.63333333 0.70000000 0.76666667 0.83333333 0.90000000 0.96666667

However, the qq function does not apply any particular distribution for a set of data. If I use this qq function to get the expected pvalues, then it is identical to using uniform distribution for expected pvalues, because ppoints(15) and qunif(ppoints(15) produce same values. qunif (Quantile of Uniform Distribution) gets the inverse distribution for the probability points.

    ppoints(15)
    [1] 0.03333333 0.10000000 0.16666667 0.23333333 0.30000000 0.36666667 0.43333333 0.50000000
    [9] 0.56666667 0.63333333 0.70000000 0.76666667 0.83333333 0.90000000 0.96666667

    qunif(ppoints(15))
    [1] 0.03333333 0.10000000 0.16666667 0.23333333 0.30000000 0.36666667 0.43333333 0.50000000
    [9] 0.56666667 0.63333333 0.70000000 0.76666667 0.83333333 0.90000000 0.96666667

Does a set of pvalues always follow uniform distribution? 

If the answer to the above question is no, then this function displays probability plot with observed p values on the y axis and the fraction of data on the x axis (the scale can be raw or -log10).

I would appreciate your comments on the null hypothesis tested using this plot and also, why you are trying to use probability plot (used for one set of data) instead of theoretical quantile - quantile plot (used for two sets of data - Observed pvalues vs Expected pvalues under a particular statistical distribution).

Thank you
Sathish

**Comment by stephenturner** [comment]
Yes, the q-q plot of p-values under the null should follow a uniform distribution. Departures can be indicative of different things going on (true association, bias/stratification, etc.)
