### ISSUE TITLE
Error in axis (1, at=ticks)

### ISSUE THREAD

**Issue by bdvelie** [stephenturner/qqman#25]
Hi Stephen,

Thanks for developing such a useful tool. I've been using it for awhile and it has always worked great, but I recently ran into a problem that I can't seem to figure out. The manhattan plot function has worked and still works great on my older data sets, but on the newest one it is only working when I limit the data to one chromosome. When I expand it to multiple chromosomes (even only 2) I am continually getting the following error:

Error in axis(1, at = ticks, labels = labs, ...) : 
  no locations are finite
In addition: Warning messages:
1: In min(d[d$CHR == i, ]$pos) :
  no non-missing arguments to min; returning Inf
2: In max(d[d$CHR == i, ]$pos) :
  no non-missing arguments to max; returning -Inf
3: In min(d[d$CHR == i, ]$pos) :
  no non-missing arguments to min; returning Inf
4: In max(d[d$CHR == i, ]$pos) :
  no non-missing arguments to max; returning -Inf
Error in axis(1, at = ticks, labels = labs, ...) : 
  no locations are finite

I've tried to sort through it and solve the problem, but I've had no luck. As far as I'm aware the data is in a suitable format and matches all the other files I've used before. At this point I've been staring at it so much even if it were something simple I don't think I'd see it. Any thoughts on what may be causing the problem?

Brandon

**Comment by bdvelie** [comment]
Forgot to paste a link to some sample data

https://gist.githubusercontent.com/bdvelie/71d9245df7e9a21916f7/raw/Sample

**Comment by stephenturner** [comment]
Hmm, I'll keep this issue open for now, but here's a temporary fix for you. It looks like the trouble is happening because you only have SNPs for chromosome 3 and 8. I'm not sure off hand if the error is because you're not starting at 1, or if it's because you're "missing" SNPs for 4, 5, 6 and 7. Either way, I should generalize the code more. 

But in the meantime, here's a hack. Clobber the data by replacing the 3's with 1s, and the 8s with 2s, draw the plot, but pass a character vector to the `chrlabs` argument. Like this:

```r
library(qqman)
d <- read.table("Sample.txt", header=TRUE)
d$CHR[d$CHR==3] <- 1
d$CHR[d$CHR==8] <- 2
manhattan(d, chrlabs=c("3", "8"))
```

![rplot](https://cloud.githubusercontent.com/assets/460076/7522836/c8f8620e-f4c5-11e4-832c-33180f74ce1f.png)

**Comment by bdvelie** [comment]
Hi Stephen,

Thanks for the quick reply. My apologies, but I should have explained it
better. I do have SNPs for chromosomes 1-26. The file I sent was just a
sample, but I also couldn't get it to work with all the snp array data. It
is the new equine array so over 670000 snps. Interestingly, the qqplot
function works fine with the entire data set. It just seems to be the
manhattan plot that isn't happy.

Thanks for the script. I'm going to have another go at it today after
having slept on it and see what I can figure out.

Cheers,

Brandon

**Comment by bdvelie** [comment]
Hi Stephen,

Thanks for the help. I'm still not sure what was causing the problem yesterday, but the hack works great. Additionally, when I ran it today on the entire dataset (1-31 chr) it worked perfectly fine using the exact same file that was giving the error yesterday. Perhaps it was just something with R that resolved itself.

Thanks again for the help,

Brandon

**Comment by zx8754** [comment]
I am getting the same error, when I exclude chr1.

**Comment by stephenturner** [comment]
@zx8754 please post some example data and code as a github gist.

**Comment by zx8754** [comment]
@stephenturner Here is an example code to reproduce the error:

```r
library(dplyr)
library(qqman)

#using @bdvelie' data
x <- read.table("https://gist.githubusercontent.com/bdvelie/71d9245df7e9a21916f7/raw/Sample",header=TRUE) %>% 
  select(CHR,SNP,BP,P)

head(x)
#   CHR          SNP    BP        P
# 1   3 AX-104433016  3525 0.870700
# 2   3 AX-104944723  4679 0.093030
# 3   3 AX-104996406  6794 0.706400
# 4   3 AX-103330248  7003 0.090690
# 5   3 AX-103033987  8340 0.561400
# 6   3 AX-103305412 31255 0.008776

table(x$CHR)
#     3     8 
# 21185 17331 

#add couple of dummy SNPs to chr 1
x_fix <- rbind(
  data.frame(CHR=c(1,1,1),
             SNP=paste0("snp",1:3),
             BP=1:3,
             P=c(0.5,0.003,0.00002)),
  x)

table(x_fix$CHR)
# 1     3     8 
# 3 21185 17331 

manhattan(x) #gives error
manhattan(x_fix) #no problems :)

```

**Comment by stephenturner** [comment]
It's a hack, but this works. Obviously need to fix this so `manhattan(x)` just works.

```r
library(dplyr)
library(qqman)

x <- read.table("https://gist.githubusercontent.com/bdvelie/71d9245df7e9a21916f7/raw/Sample",
                header=TRUE) %>% 
  tbl_df %>% 
  select(CHR,SNP,BP,P)

x %>% arrange(CHR, BP) %>% 
  mutate(realCHRs=CHR) %>% 
  mutate(CHR=factor(CHR, labels=1:n_distinct(CHR)) %>% as.numeric) %>% 
  manhattan(chrlabs=unique(.$realCHRs) %>% as.character)
```

**Comment by berg2015** [comment]
Hi Stephen,

As a follow up (kind of) to the problems raised above, may I ask if are you considering changing your code to accept alphanumeric characters? For example, I use chromosomes that are in digit+letter format (1R, 2R, etc) and qqman struggles to accept this format both in the input file, and also later when trying to change them to 1R, 2R, etc using 'chrlabs'. This change would probably benefit a lot others like me.

I also tried both hacks you suggested above, but they aren't working in my case. I thought at least the first hack (replacing each chromosome number manually with my labels) should definitely work, but no.
