### ISSUE TITLE
subsetting to chromosome for the plot isn't working right

### ISSUE THREAD

**Issue by ehscholl** [stephenturner/qqman#26]
Hello- 

I follow the tutorial as written, and when I get to the part where I'm trying to plot just a single chromosome I do not get what is posted on http://www.gettinggeneticsdone.com/2014/05/qqman-r-package-for-qq-and-manhattan-plots-for-gwas-results.html

Specifically, I use the command:

manhattan(subset(gwasResults, CHR==1))

(or alternatively manhattan(subset(gwasResults, CHR==3)) )

and I get an x-axis that goes from -1.0 to 1.0 and all of the values are "piled" near the 0.0 mark (as you might expect, since they only go to 1500, and the axis is in MB)

Adding in an "xlim=c(0,0.0015)" does help, but even then it appears to go to .0011, despite the fact that the bp goes to 1500.

manhattan(gwasResults) gives me the correct plot.

Any idea what's gone wrong here?

**Comment by timknut** [comment]
In an older version qqman, when dealing with real basepair data, will display basepairs as Mbp for the regional plots. 
I think updating to the latest version will fix the tutorial output.
