### ISSUE TITLE
adding background color

### ISSUE THREAD

**Issue by ckanag** [stephenturner/qqman#28]
I was wondering if you had any input on how the attached plot could be improved aesthetically.I do not have many markers in my plot because it only uses a subset of markers that were identified as being polymorphic between two strains of mice. Is it possible to add a different (alternating) colored background behind each chromosome?

![manhattan plots](https://cloud.githubusercontent.com/assets/12764259/8008812/708f981c-0b72-11e5-8ef3-6040b88119ec.png)

**Comment by stephenturner** [comment]
You probably could in some way but I'd advise against it. Bad [data-ink](http://www.infovis-wiki.net/index.php/Data-Ink_Ratio) ratio.
