### ISSUE TITLE
add gene names to manhattan?

### ISSUE THREAD

**Issue by kippakers** [stephenturner/qqman#31]
I would love to be able to label points on a manhattan plot above some -log p-value threshold.  I can't parse how manhattan determines the X axis position however.  Do you think adding a label option is feasible, or perhaps you know a good workaround?  
Thanks!

**Comment by stephenturner** [comment]
Install the package from github. 

```r
library(devtools)
install_github("stephenturner/qqman")
```

Then see the vignette. Specifically, the section around:

```r
manhattan(gwasResults, annotatePval = 0.01)
```

![image](https://cloud.githubusercontent.com/assets/460076/9448407/73cfe8a6-4a6a-11e5-918a-97ba4e367ab9.png)
