### ISSUE TITLE
About return value

### ISSUE THREAD

**Issue by zjf19870628** [stephenturner/qqman#32]
Hi Stephen, 
one small suggestion. Now the return values of manhattan() and qq() are empty. I think if they can return the coordinates of the points, that will be very helpful for following edit, for example, adding text. I know I can edit the source code and create my own function, but if you add this feature into the package directly, it is more helpful.

**Comment by stephenturner** [comment]
can you give an example of how you do this?

**Comment by zjf19870628** [comment]
For qq(), I copied the source code and added "return(list(x = e, y = o))"
to the end. So I can use this list to add text to the qq plot. Similarly,
for manhattan(), I added "return(d)" to the source code.

**Comment by stephenturner** [comment]
thanks. i'll add this to the next version.


Stephen
