### ISSUE TITLE
Label snps feature request

### ISSUE THREAD

**Issue by bbanbury** [stephenturner/qqman#33]
Hi there, thanks for the great package.  I just have a feature request to label snps of interest with text, similar to the highlight feature. This would help me not have to use the text() function and figure out axes.

**Comment by stephenturner** [comment]
thanks for the suggestion. next time i update qqman i'll consider adding this.

**Comment by bbanbury** [comment]
Awesome. Meanwhile I hacked your code a bit and was able to get it to work for me.  :)  Best wishes!
