### ISSUE TITLE
Draw a vertical line on GWAS plot

### ISSUE THREAD

**Issue by ubs717** [stephenturner/qqman#36]
Hi Stephen,
Thanks for the easy, quick, useful package qqman, I love it.
I have a question that is it possible to draw a vertical line to indicate specific location, like the location of gene?
For example draw a line at Chromosome 2, position 1000000 bp.

Best,
Shu-Yun

**Comment by stephenturner** [comment]
You'll have to get into the code, probably around [line 186](https://github.com/stephenturner/qqman/blob/8b462ed0e17d0f51b4027f65ad574690cc020796/R/manhattan.R#L186), and add something like `abline(v=d$pos[x])` where `x` is the position of interest, calculated from the Chr/bp.
