### ISSUE TITLE
Manhattan plot with many scaffold numbers

### ISSUE THREAD

**Issue by chung154** [stephenturner/qqman#39]
Dear Stephen,

Thanks for this useful package.
I’m wondering if there is a way to create a manhattan plot for a gwas result without chromosome numbers.  The reference genome of interest does not contain chromosome numbers but scaffold numbers ranging from 1 to 23919.  Some scaffolds have 3-500 SNPs but other scaffolds contains a few SNPs.
To make a manhattan plot, I used scaffold numbers instead of chromosome numbers.
But I got many warning messages:

There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In min(d[d$CHR == i, ]$pos) : no non-missing arguments to min; returning Inf
2: In max(d[d$CHR == i, ]$pos) : no non-missing arguments to max; returning -Inf
3: In min(d[d$CHR == i, ]$pos) : no non-missing arguments to min; returning Inf
4: In max(d[d$CHR == i, ]$pos) : no non-missing arguments to max; returning -Inf
5: In min(d[d$CHR == i, ]$pos) : no non-missing arguments to min; returning Inf
6: In max(d[d$CHR == i, ]$pos) : no non-missing arguments to max; returning -Inf

Could you help me fix this problem?
Thank you.

**Comment by stephenturner** [comment]
Try something like this.

```r
library(qqman)
gwasResults$CHR <- as.numeric(factor(gwasResults$CHR, labels=1:length(unique(gwasResults$CHR))))
manhattan(gwasResults, chrlabs=rep("", length(unique(gwasResults$CHR))))
```

![image](https://cloud.githubusercontent.com/assets/460076/14867889/c2842fa2-0c98-11e6-8eff-75f7c4a8633d.png)

**Comment by chung154** [comment]
It is working well.
Thank you very much for your help.
