### ISSUE TITLE
Gaps between Chromosomes

### ISSUE THREAD

**Issue by BOUDHRIOUA** [stephenturner/qqman#41]
Hi, 
Thank you for this package, it is very helpful, I used it to create a plot from my Gapit Ddata for a GWAS on Soybean (12 chromosomes), the problem that am keep having Gaps between my chromosomes.
[Rplot.pdf](https://github.com/stephenturner/qqman/files/245805/Rplot.pdf). 
I tried to change the chrlabs but nothing change. I am new to R and I am not sure that am doing the right things. 
I really need your help 
Thanks

**Comment by stephenturner** [comment]
Looks like it has to do with your positions. Eg if all your chr1 snps have positions 1-100, then all your chr2 snps have pos 2000-2100, then you'll have a 1900-bp gap between the end of chr1 and the start of chr2.
