### ISSUE TITLE
suggestive and genome wide lines

### ISSUE THREAD

**Issue by mcoignet** [stephenturner/qqman#46]
Hello,

I have tried using the package itself in R as well as using the original source code but for some reason, I keep getting a line at 1e-1 (example attached). Looking at the code, there is no reason for this to happen, but I have tried with multiple datasets and get the same problem for both lines (lines change color based on which line I choose, but remains in that spot).

Any help understanding this would be appreciated!

Thank you,

Marie
[test.pdf](https://github.com/stephenturner/qqman/files/521808/test.pdf)

**Comment by stephenturner** [comment]
Please post some example data and your code as a github gist and link to it
here. Thanks.

**Comment by mcoignet** [comment]
Here is some of the plink result data that I have used with this package before. It was working not long ago, perfectly!

Thank you so much for your help,

Marie

[am_reg_cand_assoc_log.txt](https://github.com/stephenturner/qqman/files/523744/am_reg_cand_assoc_log.txt)
[example_sturner.txt](https://github.com/stephenturner/qqman/files/523745/example_sturner.txt)

**Comment by mcoignet** [comment]
With that data file, it is necessary to run your source code with the correction for missing chromosomes, apologies for not including that in the code lines!

**Comment by stephenturner** [comment]
The correct argument to `suggestiveline` is the value at which to draw the line. By default this line is at 5e-8. You can see that below, where the blue line is drawn at y=5 (-log10 scale). You can change this to whatever you want, e.g. below.

```r
library(qqman)
d <- read.table("https://github.com/stephenturner/qqman/files/523744/am_reg_cand_assoc_log.txt", header=TRUE)
d <- na.omit(d)
manhattan(d)
```

![image](https://cloud.githubusercontent.com/assets/460076/19318305/3035ca5e-9076-11e6-9092-d7f429607900.png)


```r
# for example, at y=3
manhattan(d, suggestiveline=-log10(1e-3))
```

![image](https://cloud.githubusercontent.com/assets/460076/19318317/38661044-9076-11e6-8ed0-04ea61badd38.png)

**Comment by mcoignet** [comment]
Ah I see now the flaw in my thinking.. Thank you so much for clearing this up!

Marie Coignet

Dept. of Cancer Prevention & Control
Roswell Park Cancer Institute
Carlton House 345, ext. 8596
Tel. (716) 479-0809

________________________________
