### ISSUE TITLE
Feature Request: Annotate SNPs Set Font Size

### ISSUE THREAD

**Issue by ParsaAkbari** [stephenturner/qqman#47]
When I use the annotatePval and/or annotateTop flags the annotations of SNPs seem to have very small font size. It would be great if it would be possible to modulate this?

Thanks for all your work on qqman so far.

**Comment by stephenturner** [comment]
i believe you can modify the `cex=.45` argument on [line 206](https://github.com/stephenturner/qqman/blob/ab8e05f18e3d4888c84c45ac912295742eb2c055/R/manhattan.R#L206)
