### ISSUE TITLE
Warning: plot with P-values off by a factor of ~10

### ISSUE THREAD

**Issue by mrmousel** [stephenturner/qqman#49]
Stephen,

This is a very handy script when it works.  Currently, I am trying to plot ~528241 SNP and once I removed all 0 CHR, BP, and P, R will produce a plot but it appears to be 10 fold less than what the P-vaules are in the text file.   I have received the following errors:

Warning messages:
1: In min(d[d$CHR == i, ]$pos) :
  no non-missing arguments to min; returning Inf
2: In max(d[d$CHR == i, ]$pos) :
  no non-missing arguments to max; returning -Inf

Any help would be greatly appreciated!  Here is the text file I have been using:

[HD473EntMH.txt](https://github.com/stephenturner/qqman/files/691000/HD473EntMH.txt)

Thanks!

**Comment by stephenturner** [comment]
I don't see the "10-fold less" problem.

![image](https://cloud.githubusercontent.com/assets/460076/21768784/70bfdb00-d649-11e6-829a-d269d418c1d2.png)


The warning comes in because you don't have any data on chr 24. This is a known issue.

**Comment by mrmousel** [comment]
Stephen,

Thank you for your prompt response.  However, if you sort the data file by P-value there are 5 SNP with 10x-8 values and 9 at 10-7.  The plot created does not seem to reflect these P-values.  For the number of SNP I am testing, multiple sample testing correction indicates that SNP at 10x-8 and less are significant.  

Thank you!

**Comment by stephenturner** [comment]
When you take the -log10 of those you get the same values you see in the plot above.

```
> d %>% 
+   arrange(P) %>% 
+   head() %>% 
+   mutate(neglog10p=-1*log10(P))
                  SNP CHR        BP        P neglog10p
1 oar3_OAR15_75956504  15  75956504 3.56e-08  7.448550
2 oar3_OAR3_146494695   3 146494695 4.54e-08  7.342944
3 oar3_OAR3_146509933   3 146509933 4.54e-08  7.342944
4 oar3_OAR2_127168174   2 127168174 7.33e-08  7.134896
5 oar3_OAR2_127145912   2 127145912 7.88e-08  7.103474
6 oar3_OAR15_76031046  15  76031046 1.09e-07  6.962574
```
