### ISSUE TITLE
Error in plot.window(...) : need finite 'ylim' values

### ISSUE THREAD

**Issue by elcansaito** [stephenturner/qqman#51]
I know this has been seen before but I can´t figure it out what is the problem. 

> str(a2)
'data.frame':	131012 obs. of  4 variables:
 $ SNP: chr  "S1_157465" "S1_222471" "S1_222588" "S1_222877" ...
 $ CHR: num  1 1 1 1 1 1 1 1 1 1 ...
 $ BP : int  157465 222471 222588 222877 237571 264849 643082 650740 766208 766209 ...
 $ P  : num  0.05848 0.00855 0.30751 0.10895 0.07547 ...

> manhattan(a2)
Error in plot.window(...) : need finite 'ylim' values

Even If I remove P values larger than 1 it doesn´t work. 
Any help?

Thanks in advance stephen,
J

[Example_qqman.RData 2.zip](https://github.com/stephenturner/qqman/files/854013/Example_qqman.RData.2.zip)

**Comment by stephenturner** [comment]
P-values need to be between 0 and 1.

**Comment by elcansaito** [comment]
Hi Stephen,

Thanks for your reply. I indicated your suggestion in my first  post. In the attached file values are between 0 and 1 and it still doesn´t work. It might another thing. 

Thanks,
J
