### ISSUE TITLE
warning for annotatePval

### ISSUE THREAD

**Issue by ruoxichen5** [stephenturner/qqman#52]
Hi Dr. Turner,

I was trying to annotate some significant SNPs on manhattan plot, but ran into the warnings saying" 1: In plot.window(...) : "annotatePval" is not a graphical parameter
2: In plot.window(...) : "annotateTop" is not a graphical parameter
3: In plot.xy(xy, type, ...) : "annotatePval" is not a graphical parameter
4: In plot.xy(xy, type, ...) : "annotateTop" is not a graphical parameter
5: In axis(side = side, at = at, labels = labels, ...) :
  "annotatePval" is not a graphical parameter
" 
and no SNPs were annotated. 

The following is my code:
manhattan(twas_results, chr = "CHR", bp = "BP", p = "P", snp = "SNP",cex = 0.5, cex.axis = 0.8, suggestiveline = F, genomewideline = F, annotatePval = 0.00000005, annotateTop = FALSE, ylim=c(0, 100))

Would you please advise me on this?

Thanks

Ruoxi

**Comment by stephenturner** [comment]
You'll have to drop in some example data.

**Comment by ruoxichen5** [comment]
Hi Dr. Turner,

Thanks for the prompt reply. There is part of my data, I have about 8000
rows in input data.

SNP CHR BP P
ABHD16B 20 62494321 0.358035755241438
ABP1 7 150558169 0.595108204391818
ADAT3 19 1911990 0.0803252149101939
AGPHD1 15 78829700 0.444993763028434
AGXT2L2 5 177655000 0.135749742417392
AKD1 6 109996954 0.553749875018411
AMIGO3 3 49758100 0.041867523723716
ANKRD5 20 10036300 0.0720726947708967
ATP1A1OS 1 116949000 0.231264358397384
ATP6V1G2 6 31513800 4.05091027872387e-15
ATPBD4 15 35830500 0.165031771714689
BAHCC1 17 79430709 0.587815635441753
BLOC1S1 12 56113439 0.257339476933129

I am actually trying to plot the p-values for genes in association studies.
So, earlier, when I said "SNP", I meant gene. I am trying to label the
significant genes. The plot looks nice, except no annotation shown.

Thanks very much

Ruoxi

**Comment by stephenturner** [comment]
works for me.

```r
library(qqman)
d <- read.table(text=
"SNP CHR BP P
ABHD16B 20 62494321 0.358035755241438
ABP1 7 150558169 0.595108204391818
ADAT3 19 1911990 0.0803252149101939
AGPHD1 15 78829700 0.444993763028434
AGXT2L2 5 177655000 0.135749742417392
AKD1 6 109996954 0.553749875018411
AMIGO3 3 49758100 0.041867523723716
ANKRD5 20 10036300 0.0720726947708967
ATP1A1OS 1 116949000 0.231264358397384
ATP6V1G2 6 31513800 4.05091027872387e-15
ATPBD4 15 35830500 0.165031771714689
BAHCC1 17 79430709 0.587815635441753
BLOC1S1 12 56113439 0.257339476933129", header=TRUE)
manhattan(d, annotatePval = .0001)
```

![image](https://cloud.githubusercontent.com/assets/460076/24267292/37487370-0fe0-11e7-8c60-8c75cfae2db2.png)
