### ISSUE TITLE
Column CHR not found

### ISSUE THREAD

**Issue by reddamez** [stephenturner/qqman#53]
Hello Stephen,

Thanks for the very helpful package. 
Sorry but I have a basic question. This is the first time I use it to display my gwas results but I am always getting the error "Column CHR not found". Given that I have all the four columns (SNP, CHR, BP, P) numerical (except SNP) in my input file.

Thanks a lot for your help,

Reda

**Comment by stephenturner** [comment]
You'll have to leave some example data.

**Comment by reddamez** [comment]
Hi Stephen,
This is the file I am using.
Thanks,
Reda
[Uploading mydata.txt…]()

**Comment by stephenturner** [comment]
there's no data attached only a link to this page.
