### ISSUE TITLE
Question: how do I get all the chromosomes labels displayed on the x-axis?

### ISSUE THREAD

**Issue by swvanderlaan** [stephenturner/qqman#56]
Hi,
For some reason, not all the chromosome labels are printed on the x-acis: 1 through 16 are, than 17 is omitted, and than 18 and 19 are, than 20 is omitted and 21 through Y are. So, all the dots (p-values/SNPs) are printed, just not the chromosome labels.
Naively I just made the width larger, but that didn't work.

How do I go about having those labels printed?

Thanks.

**Comment by stephenturner** [comment]
I think simply increasing the figure size will help.

**Comment by swvanderlaan** [comment]
Thanks. Do you have a suggestion as to how to force R to print all chromosome labels?

**Comment by stephenturner** [comment]
The only way I know how is to increase the figure size.
