### ISSUE TITLE
Error due to very very small and/or NA P values

### ISSUE THREAD

**Issue by zjuwhw** [stephenturner/qqman#60]
```
library(qqman)
gwasResults$P[1] = 1e-400
manhattan(gwasResults)
```

Error message:
```
Error in plot.window(...) : need finite 'ylim' values
```

**Comment by stephenturner** [comment]
Not sure the best way to handle this - I don't think you want the y-axis to go all the way up to 400. I might suggest some pre-processing to cap extraordinarily low p-values to something reasonable, not sure how "accurate" p-values from parametric distributions are that are so close to zero.
