### ISSUE TITLE
Increase font size of annotation

### ISSUE THREAD

**Issue by jsreddy82** [stephenturner/qqman#61]
I am trying to annotate top hits above a certain p-value (annotateTop=T). Is there a way to increase/adjust font size of the annotated text? 
![manhattan](https://user-images.githubusercontent.com/8503178/32381887-36ddc114-c08a-11e7-902d-125f8155dcef.png)
 
Thank you for the amazing tool!

**Comment by stephenturner** [comment]
One way is to play around with the image save settings - resolution, size, dpi, etc. Unfortunately it looks like the size of the labels is hardcoded but you can very easily change line 222 of the code.

https://github.com/stephenturner/qqman/blob/master/R/manhattan.R#L222

**Comment by oalavijeh** [comment]
By change line 222 of the code do you mean copy the code into R, edit the line and run this as a function? Sorry for the basic question but I am having a same issue and have tried the above to no avail.
