### ISSUE TITLE
Column CHR not found!

### ISSUE THREAD

**Issue by geneticsmcgill** [stephenturner/qqman#62]
Hello,

I've been trying to plot some sample data with the manhattan() function and it keeps saying this:
> library(qqman)
> manhattan(ETtrait1polygenicv4)
Error in manhattan(ETtrait1polygenicv4) : Column CHR not found! 

I was wondering if you had any advice on how to proceed? Thank you so much for the wonderful program. I've attached the dataset as well. :)
[ETtrait1polygenicv4.xlsx](https://github.com/stephenturner/qqman/files/2001199/ETtrait1polygenicv4.xlsx)

**Comment by stephenturner** [comment]
Please upload a text file or paste something to https://gist.github.com/. The file you uploaded doesn't appear to be a valid excel file.

**Comment by calpan** [comment]
The posted file (which opens in Excel 2016) has column names that are lower-case where qqman expects upper-case names.  Once these are changed to upper-case, the file works fine.

**Comment by satish1907** [comment]
[SATAlLSNP1.xlsx](https://github.com/stephenturner/qqman/files/6537830/SATAlLSNP1.xlsx)
The same problem with me also. It always shows manhattan(SATAlLSNP1) : Column CHR not found!

**Comment by satish1907** [comment]
> [SATAlLSNP1.xlsx](https://github.com/stephenturner/qqman/files/6537830/SATAlLSNP1.xlsx)
> The same problem with me also. It always shows manhattan(SATAlLSNP1) : Column CHR not found!

Kindly help me in plotting this
